-- Opener Backend Database Schema
-- V1: Initial schema creation

-- Enable pgvector extension for similarity search
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

-- ===========================
-- Core User Tables
-- ===========================

-- Users table
CREATE TABLE users (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    deleted_at timestamp(6),
    updated_at timestamp(6) NOT NULL,
    version bigint,
    name varchar(255),
    role varchar(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (role IN ('USER', 'ADMIN'))
);

-- Credentials table (authentication)
CREATE TABLE credentials (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    deleted_at timestamp(6),
    updated_at timestamp(6) NOT NULL,
    version bigint,
    email varchar(255),
    failed_login_attempts integer,
    last_failed_login_at timestamp(6),
    last_login_at timestamp(6),
    locked_until timestamp(6),
    password varchar(255),
    provider varchar(255) NOT NULL,
    provider_id varchar(255),
    user_id uuid NOT NULL,
    CONSTRAINT credentials_provider_check CHECK (provider IN ('FORM', 'KAKAO')),
    CONSTRAINT uk_credentials_email UNIQUE (email),
    CONSTRAINT uk_credentials_provider_id UNIQUE (provider_id),
    CONSTRAINT uk_credentials_user_id UNIQUE (user_id),
    CONSTRAINT fk_credentials_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- User CAN (currency) table
CREATE TABLE user_cans (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    deleted_at timestamp(6),
    updated_at timestamp(6) NOT NULL,
    version bigint,
    current_cans integer,
    max_cans integer,
    user_id uuid NOT NULL
);

-- CAN Usage Log table
CREATE TABLE can_usage_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    deleted_at timestamp(6),
    updated_at timestamp(6) NOT NULL,
    version bigint,
    can_id bigint NOT NULL,
    usage_type varchar(50) NOT NULL,
    amount integer NOT NULL,
    status varchar(50) NOT NULL,
    reason varchar(255),
    CONSTRAINT can_usage_logs_usage_type_check CHECK (usage_type IN ('ISSUED', 'USED', 'REFUNDED', 'EXPIRED')),
    CONSTRAINT can_usage_logs_status_check CHECK (status IN ('SUCCESS', 'FAILED', 'PENDING'))
);

-- ===========================
-- Exam Tables
-- ===========================

-- Exams table
CREATE TABLE exams (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    deleted_at timestamp(6),
    updated_at timestamp(6) NOT NULL,
    version bigint,
    exam_type varchar(255),
    exam_year integer,
    name varchar(255),
    quantity integer,
    time_limit integer,
    CONSTRAINT exams_exam_type_check CHECK (exam_type IN ('M06', 'M09', 'CSAT'))
);

-- Questions table (with JSONB for passages and options)
CREATE TABLE questions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    deleted_at timestamp(6),
    updated_at timestamp(6) NOT NULL,
    version bigint,
    answer integer,
    category varchar(255),
    options jsonb,
    passages jsonb,
    point integer,
    question_no integer,
    question_type varchar(255),
    exam_id bigint,
    CONSTRAINT questions_category_check CHECK (category IN ('ALG', 'GEO', 'PROB', 'CALC')),
    CONSTRAINT questions_question_type_check CHECK (question_type IN ('MCQ', 'FRQ')),
    CONSTRAINT fk_questions_exam FOREIGN KEY (exam_id) REFERENCES exams(id)
);

-- Exam results table
CREATE TABLE exam_results (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    deleted_at timestamp(6),
    updated_at timestamp(6) NOT NULL,
    version bigint,
    exam_id bigint NOT NULL,
    total_score integer NOT NULL,
    total_time_spent integer NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT fk_exam_results_exam FOREIGN KEY (exam_id) REFERENCES exams(id),
    CONSTRAINT fk_exam_results_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Question results table
CREATE TABLE question_results (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_correct boolean NOT NULL,
    is_opener boolean NOT NULL DEFAULT false,
    selected integer NOT NULL,
    time_spent integer NOT NULL,
    exam_result_id bigint NOT NULL,
    question_id bigint NOT NULL,
    CONSTRAINT uk_exam_result_question UNIQUE (exam_result_id, question_id),
    CONSTRAINT fk_question_results_exam_result FOREIGN KEY (exam_result_id) REFERENCES exam_results(id),
    CONSTRAINT fk_question_results_question FOREIGN KEY (question_id) REFERENCES questions(id)
);

-- ===========================
-- Chat Tables
-- ===========================

-- Chat messages table (stores chat history)
CREATE TABLE chat_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    deleted_at timestamp(6),
    updated_at timestamp(6) NOT NULL,
    version bigint,
    messages jsonb NOT NULL,
    question_result_id bigint NOT NULL,
    CONSTRAINT uk_chat_messages_question_result UNIQUE (question_result_id),
    CONSTRAINT fk_chat_messages_question_result FOREIGN KEY (question_result_id) REFERENCES question_results(id)
);

-- ===========================
-- Indexes for Performance
-- ===========================

-- Exam results indexes
CREATE INDEX idx_exam_results_user ON exam_results(user_id);
CREATE INDEX idx_exam_results_user_exam ON exam_results(user_id, exam_id);

-- Question results indexes
CREATE INDEX idx_question_results_exam_result ON question_results(exam_result_id);
CREATE INDEX idx_question_results_question ON question_results(question_id);
